---

# Setup pacman
- name: Pacman mirrorlist setup
  copy: src=mirrorlist dest=/etc/pacman.d/
  become: true

- name: Pacman config setup
  copy: src=pacman.conf dest=/etc/
  become: true

- name: Update pacman package cache
  pacman:
    update_cache: yes
  become: true

- name: Perform full system upgrade
  pacman:
    update_cache: yes
    upgrade: yes
  become: true

# Install basic packages
- name: Install basic packages
  pacman: name={{ item }} state=present
  with_items:
      - base-devel
      - cronie
      - zsh
      - htop
      - ntp
      - openssh
      - rsync
      - curl
      - nmap
      - ntp
  become: true

# Install AUR packages
- name: Install pacaur as aur helper
  aur: name={{ item }} skip_pgp=true
  with_items:
    - cower
    - pacaur
  become: yes
  become_user: "{{ archlinux_username }}"

# Enable services
- name: Enable network time
  service: name=ntpd state=started enabled=yes
  become: true

- name: Enable cronie server
  service: name=cronie state=started enabled=yes
  become: true
