---

- name: Pacman mirrorlist setup
  ansible.builtin.copy:
    src: mirrorlist
    dest: /etc/pacman.d/

- name: Pacman config setup
  ansible.builtin.copy:
    src: pacman.conf
    dest: /etc/

- name: Update pacman package cache
  pacman:
    update_cache: true
  register: task_result
  until: task_result is success
  retries: 10
  delay: 2

- name: Perform full system upgrade
  pacman:
    update_cache: true
    upgrade: true
  register: task_result
  until: task_result is success
  retries: 10
  delay: 2
  notify:
    - rkhunter propupdate

- name: Install base packages
  pacman:
    name: "{{ base_packages }}"
    state: present
  register: task_result
  until: task_result is success
  retries: 10
  delay: 2
  notify:
    - rkhunter propupdate

- name: Install yay as aur helper
  aur:
    name: yay
    user: "{{ user.name }}"
    skip_pgp: true
  register: task_result
  until: task_result is success
  retries: 10
  delay: 2

# add task to update all packages using aur
- name: Update all packages using yay
  shell: yay -Sy --noconfirm
  register: task_result
  until: task_result is success
  retries: 10
  delay: 2

- name: Install microcode updates for intel (if necessary)
  pacman:
    name: intel-ucode
    state: present
  register: task_result
  until: task_result is success
  retries: 10
  delay: 2
  notify:
    - update grub
    - update syslinux
  when: system.processor == "intel"

- name: Install microcode updates for amd (if necessary)
  pacman:
    name: amd-ucode
    state: present
  register: task_result
  until: task_result is success
  retries: 10
  delay: 2
  notify:
    - update grub
    - update syslinux
  when: system.processor == "amd"

- name: Enable cronie server
  ansible.builtin.service: name=cronie state=started enabled=true

- name: Install YubiKey Personalization GUI
  pacman: name=yubikey-personalization-gui state=present

- name: Install smartcard libs/tools
  pacman:
    name:
      - pcsclite
      - libusb-compat
      - ccid
    state: present