---

- name: Install ntp daemon
  pacman:
    name: ntp
    state: present
  register: install
  until: install is success
  retries: 10
  delay: 2
  notify: rkhunter propupdate

- name: Configure swiss metas atomic clocks
  ansible.builtin.copy: src=ntp.conf dest=/etc/
  notify:
    - restart ntpd

- name: Make sure ntpd is stopped
  ansible.builtin.service:
    name: ntpd
    state: stopped
    enabled: true
  when: install is changed

- name: Sync time with swiss ntp metas atomic clock
  ansible.builtin.command: ntpdate ntp.metas.ch
  when: install is changed

- name: Start ntpd back up
  ansible.builtin.service:
    name: ntpd
    state: started
    enabled: true
  when: install is changed

- name: Sync time to hwclock
  ansible.builtin.command: hwclock --systohc
  when: install is changed
