---

- name: install fonts
  pacman: name={{ item }} state=present
  with_items:
    - ttf-dejavu
    - ttf-liberation
    - ttf-droid
    - fontconfig
    - xorg-font-utils

- name: Install aur fonts using pacaur
  aur: name={{ item }}
  with_items:
    - powerline-fonts-git
    - oh-my-zsh-git
  become: yes
  become_user: "{{ user.name }}"
