---

- name: install i3 windowmanager and components
  pacman:
    name: "{{ item }}"
    state: present
  with_items:
      - xorg
      - xorg-xinit
      - i3-wm
      - i3lock
      - i3status
      - dmenu
      - feh
      - dunst
      - rofi
      - compton
  register: task_result
  until: task_result is success
  retries: 10
  delay: 2

- name: install i3lock fancy
  aur:
    name: i3lock-fancy-dualmonitors-git
    user: "{{ user.name }}"
  register: task_result
  until: task_result is success
  retries: 10
  delay: 2

# Compton does not work with xsetroot
- name: install hsetroot from aur
  aur:
    name: hsetroot
    user: "{{ user.name }}"

- name: create i3wm configuration directory and util subdirectory
  file:
    name: /home/{{ user.name }}/.i3/util
    state: directory
    owner: "{{ user.name }}"
    group: "{{ user.group }}"
