---

- name: Install i3 windowmanager and components
  pacman: name={{ item }} state=present
  with_items:
      - xorg
      - xorg-xinit
      - i3-wm
      - i3lock
      - i3status
      - dmenu
      - feh
      - dunst
      - rofi

# Compton does not work with xsetroot
- name: Install hsetroot from aur
  aur: name=hsetroot user={{ user.name }}

- name: Create i3wm configuration directory and util subdirectory
  file: name=/home/{{ user.name }}/.i3/util state=directory owner={{ user.name }} group={{ user.group }}
