---

- name: Install i3 windowmanager and components
  pacman: name={{ item }}
  with_items:
      - xorg
      - xorg-xinit
      - xorg-xsetroot
      - i3-wm
      - i3lock
      - i3status
      - compton
      - dunst
      - dmenu
      - feh

- name: Create i3wm configuration directory
  file: name=/home/{{ archlinux_username }}/.i3/ state=directory owner={{ archlinux_username }} group=users
  become: true

- name: Configure i3wm
  copy: src=i3config dest=/home/{{ archlinux_username }}/.i3/config owner={{ archlinux_username }} group=users
  become: true

- name: Configure i3status
  copy: src=i3status dest=/home/{{ archlinux_username }}/.i3/i3status owner={{ archlinux_username }} group=users
  become: true

- name: Configure xinitrc
  copy: src=xinitrc dest=/home/{{ archlinux_username }}/.xinitrc owner={{ archlinux_username }} group=users
  become: true
