---

# Setup pacman
- name: Pacman mirrorlist setup
  copy: src=mirrorlist dest=/etc/pacman.d/
  become: true

- name: Pacman config setup
  copy: src=pacman.conf dest=/etc/
  become: true

- name: Update pacman packages
  command: /usr/bin/pacman -Syy --noconfirm
  become: true

- name: Perform full upgrade
  command: /usr/bin/pacman -Su --noconfirm
  become: true

# Install basic packages
- name: Install basic packages
  pacman: name={{ item }} state=present
  with_items:
      - cronie
      - zsh
      - htop
      - ntp
      - openssh
      - rsync
      - curl
      - nmap
      - ntp
      - ufw

# Install aur packages
- name: Install aur packages
  aur: name={{ item }}
  with_items:
    - puppet-lint
    - powerline-fonts-git
    - oh-my-zsh-git

# Enable services
- name: Enable network time
  service: name=ntpd state=started enabled=yes
  become: true

- name: Enable cronie server 
  service: name=cronie state=started enabled=yes
  become: true

# Run all other tasks
- import_tasks: shell.yml
- import_tasks: fonts.yml
- import_tasks: network.yml
- import_tasks: vim.yml
- import_tasks: terminal.yml
- import_tasks: i3.yml
