---

- name: Install oh-my-zsh-git and optional dependencies from AUR
  aur: name={{ item }} user={{ user.name }}
  with_items:
      - oh-my-zsh-git
      - oh-my-zsh-powerline-theme-git
  register: omzinstall

- name: Install ZSH with completion and syntax
  pacman: name={{ item }} state=present
  with_items:
      - zsh
      - zsh-completions
      - zsh-syntax-highlighting
  register: zshinstall

- name: Change shell to ZSH
  user: name={{ user.name }} shell={{ user.shell }}
  when: zshinstall.changed

- name: Apply ZSH configuration for user root as well
  copy: src=zshrc dest=/root/.zshrc owner=root group=root

- name: Apply ZSH configuration for user {{ user.name }}
  copy: src=zshrc dest=/home/{{ user.name }}/.zshrc owner={{ user.name }} group={{ user.group }}

- name: Configure oh-my-zsh Agnoster theme folder view
  lineinfile:
      path: "/usr/share/oh-my-zsh/themes/agnoster.zsh-theme"
      regexp: "'%~'"
      line: "prompt_segment blue black '%2~'"
  when: omzinstall.changed

- name: Ensure the last working dir folder is present
  file: path=/home/{{ user.name }}/.cache/oh-my-zsh/last-working-dir owner={{ user.name }} group={{ user.group }}
