---

- name: Install ZSH with completion and syntax
  pacman: name={{ item }} state=present
  with_items:
      - zsh
      - zsh-completions
      - zsh-syntax-highlighting
  become: true

- name: Change shell to ZSH
  user: name={{ archlinux_username }} shell=/bin/zsh
  become: true

- name: Apply ZSH configuration for user root
  copy: src=zshrc dest=/root/.zshrc owner=root group=root
  become: true

- name: Apply ZSH configuration for user {{ archlinux_username }}
  copy: src=zshrc dest=/home/{{ archlinux_username }}/.zshrc owner={{ archlinux_username}} group=users
  become: true

- name: Configure oh-my-zsh Agnoster theme folder view
  lineinfile:
      path: "/usr/share/oh-my-zsh/themes/agnoster.zsh-theme"
      regexp: "'%~'"
      line: "prompt_segment blue black '%2~'"
  become: true
