---

- name: Install ZSH with completion and syntax
  pacman: name={{ item }} state=present
  with_items:
      - zsh
      - zsh-completions
      - zsh-syntax-highlighting

- name: Change shell to ZSH
  user: name={{ user.name }} shell={{ user.shell }}

- name: Apply ZSH configuration for user root as well
  copy: src=zshrc dest=/root/.zshrc owner=root group=root

- name: Apply ZSH configuration for user {{ user.name }}
  copy: src=zshrc dest=/home/{{ user.name }}/.zshrc owner={{ user.name }} group={{ user.group }}
