---

- name: install vim
  pacman:
    name: vim
    state: present

- name: install gruvbox theme
  aur:
    name: vim-gruvbox-git
    user: "{{ user.name }}"

- name: install vscodium
  aur:
    name: vscodium-bin
    user: "{{ user.name }}"

- name: install vscode
  aur:
    name: visual-studio-code-bin
    user: wieger

- name: install vscodium extensions
  ansible.builtin.command: "vscodium --install-extension {{ item }}"
  become_user: "{{ user.name }}"
  register: ext_install
  changed_when: ext_install.rc != 0
  with_items:
    - asciidoctor.asciidoctor-vscode
    - gulajavaministudio.mayukaithemevsc
    - k--kato.intellij-idea-keybindings
    - ms-python.python
    - ms-toolsai.jupyter
    - ms-toolsai.jupyter-keymap
    - ms-toolsai.jupyter-renderers
    - rebornix.ruby
    - redhat.java
    - ms-azuretools.vscode-docker
    - redhat.vscode-yaml
    - redhat.ansible
    - mattiasbaake.vscode-snippets-for-ansible
    - njpwerner.autodocstring
    - eamodio.gitlens
    - onlyutkarsh.git-config-user-profiles
    - robole.markdown-snippets
    - gpoore.codebraid-preview
    - esbenp.prettier-vscode
    - streetsidesoftware.code-spell-checker
    - waderyan.gitblame
    - wingrunr21.vscode-ruby
