---

- name: Install linux-hardened and hardened headers
  pacman:
    name:
      - linux-hardened
      - linux-hardened-headers
    state: present
  notify:
    - update grub
    - update syslinux

- name: Push mkinitcpio configuration and regenerate initramfs
  template:
    src: mkinitcpio.conf.j2
    dest: /etc/mkinitcpio.conf
  notify:
    - regenerate initramfs
