- name: pacman install development tools
  pacman:
    name:
      - kubectl
      - helm
      - kustomize
      - docker
      - docker-compose

- name: Create "docker" group
  ansible.builtin.group:
    name: docker
    state: present

- name: Add remote user to "docker" group
  ansible.builtin.user:
    name: "{{ user.name }}"
    groups: docker
    append: true

- name: enable docker service
  ansible.builtin.service:
    name: docker
    state: started
    enabled: true
