- name: download rvm script
  ansible.builtin.uri:
    url: https://get.rvm.io
    dest: /tmp/rvm-install
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    mode: "770"

- name: install rvm
  become_user: "{{ user.name }}"
  ansible.builtin.command: "/tmp/rvm-install"
  register: rvm_install
  changed_when: rvm_install.rc != 0

- name: install ruby 2.7
  become_user: "{{ user.name }}"
  ansible.builtin.command: "/home/{{ user.name }}/.rvm/bin/rvm install 2.7"
  register: ruby_install
  changed_when: ruby_install.rc != 0
