---

- name: Install gimp
  pacman:
    name:
      - gimp
      - darktable
      - rawtherapee
      - shotwell
    state: present
  register: task_result
  until: task_result is success
  retries: 10
  delay: 2

- name: Jail gimp
  file: src=/usr/bin/firejail
        dest=/usr/local/bin/gimp
        state=link
  tags:
    - firejail

- name: Jail darktable
  file: src=/usr/bin/firejail
        dest=/usr/local/bin/darktable
        state=link
  tags:
    - firejail

- name: Jail rawtherapee
  file: src=/usr/bin/firejail
        dest=/usr/local/bin/rawtherapee
        state=link
  tags:
    - firejail

- name: Jail shotwell
  file: src=/usr/bin/firejail
        dest=/usr/local/bin/shotwell
        state=link
  tags:
    - firejail
