---

- name: Install telegram-desktop
  pacman: name=telegram-desktop state=present

- name: Jail telegram-desktop
  file: src=/usr/bin/firejail
        dest=/usr/local/bin/telegram-desktop
        state=link
  tags:
    - firejail
