---
- name: Install signal-desktop and discord
  pacman:
    name:
      - signal-desktop
      - discord
    state: present
  register: task_result
  until: task_result is success
  retries: 10
  delay: 2

- name: Install Slack Desktop
  aur:
    name: slack-desktop
    user: wieger