---

- name: Install macchanger
  pacman: name=macchanger state=present
  notify:
    - rkhunter propupdate

- name: Create systemd unit for macchanger
  copy: src=macspoof@.service dest=/etc/systemd/system/

- name: Take down all interfaces
  net_interface: name={{ item }} state=down enabled=false
  with_items:
    - "{{ ansible_interfaces }}"
  when: item != 'lo'

- name: Enable the macspoof service for all interface
  command: "ip link set dev {{ item }} down"
  with_items:
    - "{{ ansible_interfaces }}"
  when: item != 'lo'

- name: Bring all interfaces back up
  command: "ip link set dev {{ item }} up"
  with_items:
    - "{{ ansible_interfaces }}"
  when: item != 'lo'
