---

- name: rkhunter propupdate
  ansible.builtin.command: rkhunter --propupd

- name: restart ntpd
  ansible.builtin.service: name=ntpd state=restarted


- name: restart auto-cpufreq
  ansible.builtin.service: name=auto-cpufreq state=restarted
