---

- name: install teamspeak3 communication software
  pacman:
    name: teamspeak3
    state: present
  register: task_result
  until: task_result is success
  retries: 10
  delay: 2

- name: jail teamspeak3
  file:
    src: /usr/bin/firejail
    dest: /usr/local/bin/teamspeak3
    state: link
  tags:
    - firejail
