---

- name: Install alsa-utils and pulseaudio tools
  pacman:
    name: "{{ item }}"
    state: present
  register: task_result
  until: task_result is success
  retries: 10
  delay: 2
  with_items:
    - alsa-utils
    - pulseaudio
    - pulseaudio-alsa
    - pavucontrol
