---
# tasks file for docker
- name: Install Docker packages
  pacman:
    name: "{{ docker_packages }}"
    state: present
  register: task_result
  until: task_result is success
  retries: 10
  delay: 2