---

- name: Install base arch linux desktop environment
  hosts: all
  connection: local

  roles:
    - { role: network, tags: ['network'] }
    - { role: base, tags: ['base'] }
    - { role: dotfiles, tags: ['dotfiles'] }
    - { role: shell, tags: ['shell'] }
    - { role: editor, tags: ['editor'] }
    - { role: terminal, tags: ['terminal'] }
    - { role: windowmanager, tags: ['windowmanager'] }
  become: true
