---

- name: install urxvt terminal emulator
  pacman:
    name: rxvt-unicode
    state: present
  register: task_result
  until: task_result is success
  retries: 10
  delay: 2

- name: install alacritty terminal emulator
  pacman:
    name: "alacritty"
    state: present
  register: task_result
  until: task_result is success
  retries: 10
  delay: 2

- name: install kitty terminal emulator
  pacman:
    name: kitty
    state: present
  register: task_result
  until: task_result is success
  retries: 10
  delay: 2

- name: create kitty configuration directory
  file:
    dest: /home/"{{ user.name }}"/.config/kitty
    state: directory
    owner: ""{{ user.name }}""
    group: users
    mode: 0755
  become: true

- name: configure kitty
  template:
    src: kitty.conf
    dest: /home/{{ user.name }}/.config/kitty/kitty.conf
    owner: "{{ user.name }}"
    group: users
    mode: 0644
  become: true

- name: install tmux terminal multiplexer
  pacman:
    name: tmux
    state: present
  register: task_result
  until: task_result is success
  retries: 10
  delay: 2
