---

- name: Install linux-hardened and hardened headers
  pacman: name={{ item }} state=present
  with_items:
      - linux-hardened
      - linux-hardened-headers
  notify:
      - update grub
      - update syslinux
