---

- name: Install linux-hardened and hardened headers
  pacman: name={{ item }} state=present
  with_items:
      - linux-hardened
      - linux-hardened-headers
  notify:
      - update grub
      - update syslinux

- name: Create new boot entry if syslinux is used
  blockinfile:
    dest: /boot/syslinux/syslinux.cfg
    block: |
        LABEL archhardened
            MENU LABEL Arch Linux Hardened
            LINUX ../vmlinuz-linux-hardened
            APPEND cryptdevice=/dev/sda2:vg0 root=/dev/mapper/vg0-root resume=/dev/mapper/vg0-swap rw lang=en locale={{ system.locale }} vga=773 quiet splash
            INITRD ../{{ system.processor_type }}-ucode.img,../initramfs-linux-hardened.img

            LABEL archhardenedfallback
            MENU LABEL Arch Linux Hardened Fallback
            LINUX ../vmlinuz-linux-hardened
            APPEND cryptdevice=/dev/sda2:main root=/dev/mapper/main-root rw lang=en locale={{ system.locale }} quiet splash
            INITRD ../{{ system.processor_type }}-ucode.img,../initramfs-linux-hardened-fallback.img
    marker: "# {mark} ANSIBLE MANAGED BLOCK { mark }"
  when: bootloader == "syslinux"
